import { Person } from "./Models";
export const grid_data: Person[] = [
  {
    name: "Wayne Mohr",
    email: "Coleman.Johnson56@gmail.com",
    status: "inactive",
    address: "6665 Pearlie Crossing",
    bio: "Decerno cibus sollers agnitio.",
    jobTitle: "Senior Implementation Representative",
    zodiacSign: "Cancer",
  },
  {
    name: "Adrienne Lueilwitz",
    email: "Lilyan22@hotmail.com",
    status: "active",
    address: "21132 Dariana Mews",
    bio: "Capitulus atqui apparatus demergo adicio.",
    jobTitle: "Regional Assurance Supervisor",
    zodiacSign: "Scorpio",
  },
  {
    name: "Dr. Lydia Mraz",
    email: "Arnaldo.Friesen66@gmail.com",
    status: "active",
    address: "1964 Batz Coves",
    bio: "Tersus ocer corona vulticulus amicitia vulgus necessitatibus.",
    jobTitle: "Regional Implementation Facilitator",
    zodiacSign: "Scorpio",
  },
  {
    name: "Gertrude Weimann",
    email: "Pink47@yahoo.com",
    status: "inactive",
    address: "4489 Howe Landing",
    bio: "Circumvenio eius utroque carpo valens illo.",
    jobTitle: "Regional Infrastructure Designer",
    zodiacSign: "Cancer",
  },
  {
    name: "Oliver Wiegand-Ruecker",
    email: "Dejon54@hotmail.com",
    status: "inactive",
    address: "750 Donnelly Turnpike",
    bio: "Uberrime casus adinventitias architecto tres animi.",
    jobTitle: "Regional Paradigm Designer",
    zodiacSign: "Cancer",
  },
  {
    name: "Karla Terry",
    email: "Jacinto73@yahoo.com",
    status: "active",
    address: "365 Keshawn Harbor",
    bio: "Cunctatio accedo cultura villa brevis vicissitudo.",
    jobTitle: "Lead Solutions Agent",
    zodiacSign: "Aries",
  },
  {
    name: "Mr. Toby DuBuque",
    email: "Loy_Prohaska34@gmail.com",
    status: "inactive",
    address: "761 Camden Bridge",
    bio: "Sed patruus tremo depopulo talis praesentium.",
    jobTitle: "Central Assurance Producer",
    zodiacSign: "Cancer",
  },
];
